package web

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/yohnark/tadori/internal/model"
	"github.com/yohnark/tadori/internal/report"
)

// ProgressEvent is the deliberately small, UI-owned event shape used by the
// view endpoint. It is not a runtime/session contract. A future session or
// SSE adapter can translate its events into this shape without changing the
// canonical diagnostic model or the view renderer.
type ProgressEvent struct {
	ProbeName string            `json:"probe_name,omitempty"`
	State     string            `json:"state"`
	Status    model.ProbeStatus `json:"status,omitempty"`
}

// ProgressRunner is an optional adapter for a runner that can report
// presentation progress on the legacy synchronous view endpoint. The
// session/SSE runtime has its own published contract and is used by the
// browser's normal workflow; this adapter remains useful to embedders and
// deterministic tests without coupling them to session storage.
type ProgressRunner func(context.Context, model.Target, func(ProgressEvent)) model.DiagnosticReport

// DiagnosticViewModel is an additive presentation projection. Report is the
// canonical source of truth; every other field is derived from it and can be
// discarded and rebuilt. CanonicalJSON is generated by report.MarshalJSON so
// the inspector does not re-serialize or reinterpret raw evidence in the
// browser.
type DiagnosticViewModel struct {
	Report         model.DiagnosticReport   `json:"report"`
	Observations   model.Observations       `json:"observations"`
	CanonicalJSON  string                   `json:"canonical_json"`
	NetworkContext *NetworkContextView      `json:"network_context,omitempty"`
	Overall        OverallView              `json:"overall"`
	Progress       []ProgressEvent          `json:"progress"`
	Probes         []ProbeView              `json:"probes"`
	NameResolution *NameResolutionView      `json:"name_resolution,omitempty"`
	Findings       []FindingView            `json:"findings"`
	Evidence       []EvidenceView           `json:"evidence"`
	Paths          []PathView               `json:"paths"`
	Comparisons    []ProtocolComparisonView `json:"comparisons"`
}

// NetworkContextView is the presentation projection of the canonical target
// routing context. The machine-readable context remains in Report.Target;
// labels here are derived only for the browser view.
type NetworkContextView struct {
	NetworkScope               model.NetworkScope      `json:"network_scope"`
	NetworkScopeLabel          string                  `json:"network_scope_label"`
	RequestedIdentity          string                  `json:"requested_identity"`
	SelectedDestinationAddress string                  `json:"selected_destination_address,omitempty"`
	SelectedSourceInterface    string                  `json:"selected_source_interface,omitempty"`
	SelectedSourceAddress      string                  `json:"selected_source_address,omitempty"`
	EffectiveRoute             model.RouteDisposition  `json:"effective_route"`
	EffectiveRouteLabel        string                  `json:"effective_route_label"`
	RoutePrefix                string                  `json:"route_prefix,omitempty"`
	NextHop                    string                  `json:"next_hop,omitempty"`
	Gateway                    string                  `json:"gateway,omitempty"`
	RouteMetric                int                     `json:"route_metric"`
	VPNOrTunnelInvolvement     bool                    `json:"vpn_or_tunnel_involvement,omitempty"`
	VirtualAdapterInvolvement  bool                    `json:"virtual_adapter_involvement,omitempty"`
	RouteSelectionAmbiguous    bool                    `json:"route_selection_ambiguous,omitempty"`
	CompetingRoutes            []model.RouteCandidate  `json:"competing_routes,omitempty"`
	Neighbor                   *model.NeighborEvidence `json:"neighbor,omitempty"`
	Provenance                 []string                `json:"provenance,omitempty"`
	EvidenceIDs                []string                `json:"evidence_ids,omitempty"`
}

// OverallView keeps report execution status separate from diagnosis and from
// destination reachability. In particular, a complete report can still have
// a failed destination or a destination confirmed while intermediate hops
// are unobservable.
type OverallView struct {
	ExecutionStatus model.ReportStatus `json:"execution_status"`
	ExecutionLabel  string             `json:"execution_label"`
	DiagnosisState  string             `json:"diagnosis_state"`
	DiagnosisLabel  string             `json:"diagnosis_label"`
	Tone            string             `json:"tone"`
	Destination     DestinationView    `json:"destination"`
}

// DestinationView describes only endpoint evidence. It intentionally does
// not use the observability of intermediate path hops as a proxy for endpoint
// reachability.
type DestinationView struct {
	State       string   `json:"state"`
	Label       string   `json:"label"`
	Detail      string   `json:"detail"`
	ProbeNames  []string `json:"probe_names,omitempty"`
	EvidenceIDs []string `json:"evidence_ids,omitempty"`
}

type ProbeView struct {
	Name          string              `json:"name"`
	Status        model.ProbeStatus   `json:"status"`
	Tone          string              `json:"tone"`
	StatusLabel   string              `json:"status_label"`
	DurationMS    int64               `json:"duration_ms"`
	FailureReason model.FailureReason `json:"failure_reason"`
	Layer         model.Layer         `json:"layer"`
	FaultDomain   model.FaultDomain   `json:"fault_domain"`
	EvidenceIDs   []string            `json:"evidence_ids,omitempty"`
}

type FindingView struct {
	FailureReason model.FailureReason `json:"failure_reason"`
	Label         string              `json:"label"`
	Tone          string              `json:"tone"`
	Layer         model.Layer         `json:"layer"`
	FaultDomain   model.FaultDomain   `json:"fault_domain"`
	ProbeNames    []string            `json:"probe_names,omitempty"`
	EvidenceIDs   []string            `json:"evidence_ids,omitempty"`
}

type EvidenceView struct {
	ID             string             `json:"id"`
	ProbeName      string             `json:"probe_name"`
	Kind           model.EvidenceKind `json:"kind"`
	Source         string             `json:"source,omitempty"`
	CapturedAt     *time.Time         `json:"captured_at,omitempty"`
	Structured     bool               `json:"structured"`
	InspectorState string             `json:"inspector_state"`
	InspectorNote  string             `json:"inspector_note,omitempty"`
	Raw            json.RawMessage    `json:"raw"`
}

// NameResolutionView is the presentation projection of the canonical DNS
// observation. It keeps configured candidates beside the effective path so a
// configured server is not mistaken for the server that answered the query.
type NameResolutionView struct {
	RequestedName       string                          `json:"requested_name"`
	CandidateNames      []string                        `json:"candidate_names,omitempty"`
	CandidateSuffixes   []string                        `json:"candidate_suffixes,omitempty"`
	CandidateNamespaces []string                        `json:"candidate_namespaces,omitempty"`
	Paths               []NameResolutionPathView        `json:"paths,omitempty"`
	EffectivePath       *NameResolutionPathView         `json:"effective_path,omitempty"`
	A                   []string                        `json:"a,omitempty"`
	AAAA                []string                        `json:"aaaa,omitempty"`
	SelectedAddress     string                          `json:"selected_address,omitempty"`
	SelectedFamily      string                          `json:"selected_family,omitempty"`
	HostsFileEntries    []model.NameResolutionHostEntry `json:"hosts_file_entries,omitempty"`
	Limitations         []string                        `json:"limitations,omitempty"`
	EvidenceIDs         []string                        `json:"evidence_ids,omitempty"`
}

type NameResolutionPathView struct {
	State          model.NameResolutionPathState `json:"state"`
	Label          string                        `json:"label"`
	Mechanism      model.NameResolutionMechanism `json:"mechanism"`
	Resolver       string                        `json:"resolver,omitempty"`
	Interface      string                        `json:"interface,omitempty"`
	InterfaceIndex int                           `json:"interface_index,omitempty"`
	VirtualAdapter bool                          `json:"virtual_adapter,omitempty"`
	VPN            bool                          `json:"vpn,omitempty"`
	Namespace      string                        `json:"namespace,omitempty"`
	Namespaces     []string                      `json:"namespaces,omitempty"`
	PolicySource   string                        `json:"policy_source,omitempty"`
	PolicyRule     string                        `json:"policy_rule,omitempty"`
	A              []string                      `json:"a,omitempty"`
	AAAA           []string                      `json:"aaaa,omitempty"`
	Certainty      model.NameResolutionCertainty `json:"certainty"`
	Provenance     string                        `json:"provenance,omitempty"`
	EvidenceIDs    []string                      `json:"evidence_ids,omitempty"`
}

type PathView struct {
	EvidenceID              string                      `json:"evidence_id,omitempty"`
	EvidenceIDs             []string                    `json:"evidence_ids,omitempty"`
	Provenance              []string                    `json:"provenance,omitempty"`
	ProbeName               string                      `json:"probe_name"`
	Protocol                model.PathProtocol          `json:"protocol"`
	ProtocolLabel           string                      `json:"protocol_label"`
	ObservationStatus       model.PathObservationStatus `json:"observation_status"`
	ObservationTone         string                      `json:"observation_tone"`
	ObservationLabel        string                      `json:"observation_label"`
	Destination             string                      `json:"destination"`
	DestinationPort         uint16                      `json:"destination_port"`
	PortAware               bool                        `json:"port_aware"`
	DestinationReached      bool                        `json:"destination_reached"`
	DestinationTCPConnected bool                        `json:"destination_tcp_connected"`
	Hops                    []PathHopView               `json:"hops"`
	Segments                []PathSegmentView           `json:"segments"`
	Error                   string                      `json:"error,omitempty"`
}

type PathHopView struct {
	TTL         uint8              `json:"ttl"`
	State       model.PathHopState `json:"state"`
	Tone        string             `json:"tone"`
	Label       string             `json:"label"`
	Detail      string             `json:"detail"`
	Attempts    int                `json:"attempts,omitempty"`
	Responders  []ResponderView    `json:"responders"`
	EvidenceIDs []string           `json:"evidence_ids,omitempty"`
}

type ResponderView struct {
	Address            string `json:"address"`
	RTTMS              int64  `json:"rtt_ms,omitempty"`
	Response           string `json:"response,omitempty"`
	DestinationReached bool   `json:"destination_reached,omitempty"`
}

type PathSegmentView struct {
	Kind        model.PathSegmentKind `json:"kind"`
	FromTTL     uint8                 `json:"from_ttl"`
	ToTTL       uint8                 `json:"to_ttl"`
	Tone        string                `json:"tone"`
	Label       string                `json:"label"`
	Detail      string                `json:"detail"`
	Responders  []ResponderView       `json:"responders"`
	EvidenceIDs []string              `json:"evidence_ids,omitempty"`
}

type ProtocolComparisonView struct {
	Destination             string                      `json:"destination"`
	DestinationPort         uint16                      `json:"destination_port"`
	PortLabel               string                      `json:"port_label"`
	Observations            []ComparisonObservationView `json:"observations"`
	ICMPDestinationReached  bool                        `json:"icmp_destination_reached"`
	TCPDestinationReached   bool                        `json:"tcp_destination_reached"`
	TCPDestinationConnected bool                        `json:"tcp_destination_connected"`
}

type ComparisonObservationView struct {
	EvidenceID              string                      `json:"evidence_id"`
	EvidenceIDs             []string                    `json:"evidence_ids,omitempty"`
	Protocol                model.PathProtocol          `json:"protocol"`
	Status                  model.PathObservationStatus `json:"status"`
	PortAware               bool                        `json:"port_aware"`
	DestinationReached      bool                        `json:"destination_reached"`
	DestinationTCPConnected bool                        `json:"destination_tcp_connected"`
	UnobservableTTLs        []uint8                     `json:"unobservable_ttls,omitempty"`
	ResponderCount          int                         `json:"responder_count"`
}

// BuildDiagnosticView builds the UI projection from one canonical report.
// It never runs probes, changes the report, or decodes raw evidence. The
// report-level observation envelope is the workbench's normal world model;
// probe evidence remains available in the inspector as raw JSON.
func BuildDiagnosticView(diagnosticReport model.DiagnosticReport) (DiagnosticViewModel, error) {
	canonical, err := report.MarshalJSON(diagnosticReport)
	if err != nil {
		return DiagnosticViewModel{}, fmt.Errorf("marshal canonical report for UI: %w", err)
	}

	observations := model.NormalizeObservations(diagnosticReport.Observations)
	view := DiagnosticViewModel{
		Report:        diagnosticReport,
		Observations:  observations,
		CanonicalJSON: string(canonical),
		Progress:      make([]ProgressEvent, 0),
		Probes:        make([]ProbeView, 0, len(diagnosticReport.Probes)),
		Findings:      make([]FindingView, 0, len(diagnosticReport.Findings)),
		Evidence:      make([]EvidenceView, 0),
		Paths:         make([]PathView, 0),
		Comparisons:   make([]ProtocolComparisonView, 0),
	}
	if hasNetworkContext(observations.NetworkContext) {
		view.NetworkContext = buildNetworkContextView(observations.NetworkContext)
	}

	view.Overall = buildOverallView(diagnosticReport, observations)
	view.NameResolution = buildNameResolutionView(observations.NameResolution)
	for _, probe := range diagnosticReport.Probes {
		probeEvidenceIDs := evidenceIDs(probe.Evidence)
		view.Probes = append(view.Probes, ProbeView{
			Name:          probe.Name,
			Status:        probe.Status,
			Tone:          toneForProbe(probe.Status),
			StatusLabel:   labelForProbeStatus(probe.Status),
			DurationMS:    probe.Timing.DurationMS,
			FailureReason: probe.Interpretation.FailureReason,
			Layer:         probe.Interpretation.Layer,
			FaultDomain:   probe.Interpretation.FaultDomain,
			EvidenceIDs:   probeEvidenceIDs,
		})
		for _, evidence := range probe.Evidence {
			evidenceView := EvidenceView{
				ID:             evidence.ID,
				ProbeName:      probe.Name,
				Kind:           evidence.Kind,
				Source:         evidence.Source,
				CapturedAt:     evidence.CapturedAt,
				Structured:     isStructuredJSON(evidence.Raw),
				InspectorState: "available",
				Raw:            evidence.Raw,
			}
			view.Evidence = append(view.Evidence, evidenceView)
		}
	}

	for _, finding := range diagnosticReport.Findings {
		view.Findings = append(view.Findings, FindingView{
			FailureReason: finding.FailureReason,
			Label:         labelForFailureReason(finding.FailureReason),
			Tone:          toneForFailureReason(finding.FailureReason),
			Layer:         finding.Layer,
			FaultDomain:   finding.FaultDomain,
			ProbeNames:    append([]string(nil), finding.ProbeNames...),
			EvidenceIDs:   append([]string(nil), finding.EvidenceIDs...),
		})
	}

	pathInputs := make([]pathInput, 0, len(observations.Paths))
	for index, observation := range observations.Paths {
		pathInputs = append(pathInputs, pathInput{
			observation: observation,
			provenance:  observationProvenanceAt(observations.PathProvenance, index),
		})
	}
	for _, input := range pathInputs {
		view.Paths = append(view.Paths, buildPathView(input))
	}
	view.Comparisons = buildComparisons(observations.PathCorrelations, pathInputs)
	view.Progress = completedProgress(view.Probes)
	return view, nil
}

func buildNameResolutionView(observation model.NameResolutionObservation) *NameResolutionView {
	if observation.RequestedName == "" && len(observation.Paths) == 0 && observation.EffectivePath == nil {
		return nil
	}
	view := &NameResolutionView{
		RequestedName:       observation.RequestedName,
		CandidateNames:      append([]string(nil), observation.CandidateNames...),
		CandidateSuffixes:   append([]string(nil), observation.CandidateSuffixes...),
		CandidateNamespaces: append([]string(nil), observation.CandidateNamespaces...),
		A:                   append([]string(nil), observation.A...),
		AAAA:                append([]string(nil), observation.AAAA...),
		SelectedAddress:     observation.SelectedAddress,
		SelectedFamily:      observation.SelectedFamily,
		HostsFileEntries:    append([]model.NameResolutionHostEntry(nil), observation.HostsFileEntries...),
		Limitations:         append([]string(nil), observation.Limitations...),
		EvidenceIDs:         append([]string(nil), observation.EvidenceIDs...),
		Paths:               make([]NameResolutionPathView, 0, len(observation.Paths)),
	}
	for _, path := range observation.Paths {
		view.Paths = append(view.Paths, nameResolutionPathView(path))
	}
	if observation.EffectivePath != nil {
		path := nameResolutionPathView(*observation.EffectivePath)
		view.EffectivePath = &path
	}
	return view
}

func nameResolutionPathView(path model.NameResolutionPath) NameResolutionPathView {
	label := string(path.Mechanism)
	if path.Mechanism == model.NameResolutionMechanismLiteralIP {
		label = "Literal IP"
	} else if path.Mechanism == model.NameResolutionMechanismHostsFile {
		label = "Hosts file candidate"
	} else if path.VPN {
		label = "VPN / Corporate DNS"
	} else if path.Mechanism == model.NameResolutionMechanismDNS {
		label = "System DNS client"
	}
	return NameResolutionPathView{
		State:          path.State,
		Label:          label,
		Mechanism:      path.Mechanism,
		Resolver:       path.Resolver,
		Interface:      path.Interface,
		InterfaceIndex: path.InterfaceIndex,
		VirtualAdapter: path.VirtualAdapter,
		VPN:            path.VPN,
		Namespace:      path.Namespace,
		Namespaces:     append([]string(nil), path.Namespaces...),
		PolicySource:   path.PolicySource,
		PolicyRule:     path.PolicyRule,
		A:              append([]string(nil), path.A...),
		AAAA:           append([]string(nil), path.AAAA...),
		Certainty:      path.Certainty,
		Provenance:     path.Provenance,
		EvidenceIDs:    append([]string(nil), path.EvidenceIDs...),
	}
}

func buildNetworkContextView(context model.NetworkContext) *NetworkContextView {
	return &NetworkContextView{
		NetworkScope:               context.NetworkScope,
		NetworkScopeLabel:          networkScopeLabel(context.NetworkScope),
		RequestedIdentity:          context.RequestedIdentity,
		SelectedDestinationAddress: context.SelectedDestinationAddress,
		SelectedSourceInterface:    context.SelectedSourceInterface,
		SelectedSourceAddress:      context.SelectedSourceAddress,
		EffectiveRoute:             context.EffectiveRoute,
		EffectiveRouteLabel:        routeDispositionLabel(context.EffectiveRoute),
		RoutePrefix:                context.RoutePrefix,
		NextHop:                    context.NextHop,
		Gateway:                    context.Gateway,
		RouteMetric:                context.RouteMetric,
		VPNOrTunnelInvolvement:     context.VPNOrTunnelInvolvement,
		VirtualAdapterInvolvement:  context.VirtualAdapterInvolvement,
		RouteSelectionAmbiguous:    context.RouteSelectionAmbiguous,
		CompetingRoutes:            append([]model.RouteCandidate(nil), context.CompetingRoutes...),
		Neighbor:                   cloneNeighborEvidence(context.Neighbor),
		Provenance:                 append([]string(nil), context.Provenance...),
		EvidenceIDs:                append([]string(nil), context.EvidenceIDs...),
	}
}

func cloneNeighborEvidence(neighbor *model.NeighborEvidence) *model.NeighborEvidence {
	if neighbor == nil {
		return nil
	}
	copy := *neighbor
	copy.Entries = append([]model.NeighborEntry(nil), neighbor.Entries...)
	return &copy
}

func networkScopeLabel(scope model.NetworkScope) string {
	switch scope {
	case model.NetworkScopeLoopback:
		return "Loopback"
	case model.NetworkScopeLinkLocal:
		return "Link-local"
	case model.NetworkScopeSameLink:
		return "Local link"
	case model.NetworkScopePrivateRouted:
		return "Private routed"
	case model.NetworkScopeVPNTunnelRouted:
		return "VPN / tunnel routed"
	case model.NetworkScopeExternalRouted:
		return "External routed"
	default:
		return "Unknown"
	}
}

func routeDispositionLabel(disposition model.RouteDisposition) string {
	switch disposition {
	case model.RouteDispositionOnLink:
		return "On-link"
	case model.RouteDispositionRouted:
		return "Routed"
	default:
		return "Unknown"
	}
}

type pathInput struct {
	observation model.PathObservation
	provenance  model.ObservationProvenance
}

func buildOverallView(diagnosticReport model.DiagnosticReport, observations model.Observations) OverallView {
	diagnosisState := "clear"
	diagnosisLabel := "No canonical findings"
	tone := "positive"
	if len(diagnosticReport.Findings) > 0 {
		diagnosisState = "finding"
		diagnosisLabel = fmt.Sprintf("%d canonical finding%s", len(diagnosticReport.Findings), pluralSuffix(len(diagnosticReport.Findings)))
		tone = "negative"
	} else if diagnosticReport.Status == model.ReportStatusIncomplete {
		diagnosisState = "incomplete"
		diagnosisLabel = "Evidence is incomplete"
		tone = "warning"
	} else if diagnosticReport.Status == model.ReportStatusError || diagnosticReport.Status == model.ReportStatusUnknown {
		diagnosisState = "unknown"
		diagnosisLabel = "Diagnosis is unavailable"
		tone = "neutral"
	}

	return OverallView{
		ExecutionStatus: diagnosticReport.Status,
		ExecutionLabel:  labelForReportStatus(diagnosticReport.Status),
		DiagnosisState:  diagnosisState,
		DiagnosisLabel:  diagnosisLabel,
		Tone:            tone,
		Destination:     destinationView(observations),
	}
}

func destinationView(observations model.Observations) DestinationView {
	confirmed := make([]string, 0)
	reachedButNotConnected := make([]string, 0)
	failed := make([]string, 0)
	confirmedObserved := false
	reachedObserved := false
	failedObserved := false
	if observations.Transport.Connected {
		confirmedObserved = true
		confirmed = append(confirmed, observations.Transport.ProbeNames...)
	}
	if observations.Security.HandshakeComplete {
		confirmedObserved = true
		confirmed = append(confirmed, observations.Security.ProbeNames...)
	}
	if observations.Application.ResponseReceived {
		confirmedObserved = true
		confirmed = append(confirmed, observations.Application.ProbeNames...)
	}
	if observations.Transport.Applicability == model.ObservationApplicabilityApplicable && !observations.Transport.Connected && observations.Transport.FailureReason != model.FailureReasonNone {
		failedObserved = true
		failed = append(failed, observations.Transport.ProbeNames...)
	}
	for index, flow := range observations.PacketFlows {
		if flow.CaptureStatus != model.PacketCaptureStatusAvailable || (flow.Outcome == model.PacketFlowOutcomeTCPHandshakeConfirmed || flow.Outcome == model.PacketFlowOutcomeTCPSYNACK || flow.Outcome == model.PacketFlowOutcomeTCPRST) && flow.Certainty != model.EvidenceCertaintyConfirmedEndpointResponse {
			continue
		}
		switch flow.Outcome {
		case model.PacketFlowOutcomeTCPHandshakeConfirmed, model.PacketFlowOutcomeTCPSYNACK:
			confirmedObserved = true
			confirmed = append(confirmed, observationProbeNamesAt(observations.PacketFlowProvenance, index)...)
		case model.PacketFlowOutcomeTCPRST:
			reachedObserved = true
			reachedButNotConnected = append(reachedButNotConnected, observationProbeNamesAt(observations.PacketFlowProvenance, index)...)
		}
	}
	for index, path := range observations.Paths {
		if path.Protocol != model.PathProtocolTCP || !path.PortAware {
			continue
		}
		if path.DestinationTCPConnected {
			confirmedObserved = true
			confirmed = append(confirmed, observationProbeNamesAt(observations.PathProvenance, index)...)
		} else if path.DestinationReached {
			reachedObserved = true
			reachedButNotConnected = append(reachedButNotConnected, observationProbeNamesAt(observations.PathProvenance, index)...)
		} else if path.Status == model.PathObservationStatusObserved {
			failedObserved = true
			failed = append(failed, observationProbeNamesAt(observations.PathProvenance, index)...)
		}
	}
	for _, correlation := range observations.PathCorrelations {
		if correlation.TCPDestinationConnected {
			confirmedObserved = true
			confirmed = append(confirmed, pathProbeNames(observations, correlation)...)
		} else if correlation.TCPDestinationReached {
			reachedObserved = true
			reachedButNotConnected = append(reachedButNotConnected, pathProbeNames(observations, correlation)...)
		}
	}
	if confirmedObserved {
		return DestinationView{
			State: "confirmed", Label: "Destination confirmed",
			Detail:     "A canonical transport, security, application, or path observation reached the requested endpoint.",
			ProbeNames: uniqueStrings(confirmed), EvidenceIDs: destinationEvidenceIDs(observations, "confirmed"),
		}
	}
	if reachedObserved {
		return DestinationView{
			State: "reached_not_connected", Label: "Destination reached; port not connected",
			Detail:     "A canonical observation reached the destination, but the requested port did not establish a connection.",
			ProbeNames: uniqueStrings(reachedButNotConnected), EvidenceIDs: destinationEvidenceIDs(observations, "reached_not_connected"),
		}
	}
	if failedObserved {
		return DestinationView{
			State: "failed", Label: "Destination connectivity failed",
			Detail:     "The canonical transport observation reported a failure for the requested endpoint.",
			ProbeNames: uniqueStrings(failed), EvidenceIDs: destinationEvidenceIDs(observations, "failed"),
		}
	}
	if len(observations.Paths) == 0 && len(observations.PacketFlows) == 0 && len(observations.Endpoint.ProbeNames) == 0 && len(observations.Transport.ProbeNames) == 0 && len(observations.Security.ProbeNames) == 0 && len(observations.Application.ProbeNames) == 0 {
		return DestinationView{State: "unknown", Label: "Destination state unknown", Detail: "No usable endpoint observation is available."}
	}
	return DestinationView{State: "unconfirmed", Label: "Destination not confirmed", Detail: "Canonical observations do not establish requested endpoint connectivity."}
}

func destinationEvidenceIDs(observations model.Observations, state string) []string {
	ids := make([]string, 0)
	if state == "confirmed" {
		ids = append(ids, observations.Endpoint.EvidenceIDs...)
		if observations.Transport.Connected {
			ids = append(ids, observations.Transport.EvidenceIDs...)
		}
		if observations.Security.HandshakeComplete {
			ids = append(ids, observations.Security.EvidenceIDs...)
		}
		if observations.Application.ResponseReceived {
			ids = append(ids, observations.Application.EvidenceIDs...)
		}
	}
	if state == "failed" {
		ids = append(ids, observations.Transport.EvidenceIDs...)
	}
	for index, flow := range observations.PacketFlows {
		if flow.CaptureStatus != model.PacketCaptureStatusAvailable || (flow.Outcome == model.PacketFlowOutcomeTCPHandshakeConfirmed || flow.Outcome == model.PacketFlowOutcomeTCPSYNACK || flow.Outcome == model.PacketFlowOutcomeTCPRST) && flow.Certainty != model.EvidenceCertaintyConfirmedEndpointResponse {
			continue
		}
		if (state == "confirmed" && (flow.Outcome == model.PacketFlowOutcomeTCPHandshakeConfirmed || flow.Outcome == model.PacketFlowOutcomeTCPSYNACK)) || (state == "reached_not_connected" && flow.Outcome == model.PacketFlowOutcomeTCPRST) {
			ids = append(ids, observationEvidenceIDsAt(observations.PacketFlowProvenance, index)...)
		}
	}
	for index, path := range observations.Paths {
		match := state == "confirmed" && path.Protocol == model.PathProtocolTCP && path.PortAware && path.DestinationTCPConnected
		match = match || state == "reached_not_connected" && path.Protocol == model.PathProtocolTCP && path.PortAware && path.DestinationReached && !path.DestinationTCPConnected
		match = match || state == "failed" && path.Protocol == model.PathProtocolTCP && path.PortAware && path.Status == model.PathObservationStatusObserved && !path.DestinationReached
		if match {
			ids = append(ids, observationEvidenceIDsAt(observations.PathProvenance, index)...)
		}
	}
	return uniqueStrings(ids)
}

func pathProbeNames(observations model.Observations, correlation model.PathCorrelation) []string {
	result := make([]string, 0)
	for index, path := range observations.Paths {
		if path.Destination != correlation.Destination || path.DestinationPort != correlation.DestinationPort {
			continue
		}
		result = append(result, observationProbeNamesAt(observations.PathProvenance, index)...)
	}
	return result
}

func observationProvenanceAt(values []model.ObservationProvenance, index int) model.ObservationProvenance {
	if index < 0 || index >= len(values) {
		return model.ObservationProvenance{}
	}
	return values[index]
}

func observationEvidenceIDsAt(values []model.ObservationProvenance, index int) []string {
	return append([]string(nil), observationProvenanceAt(values, index).EvidenceIDs...)
}

func observationProbeNamesAt(values []model.ObservationProvenance, index int) []string {
	provenance := observationProvenanceAt(values, index)
	if provenance.ProbeName == "" {
		return nil
	}
	return []string{provenance.ProbeName}
}

func hasNetworkContext(context model.NetworkContext) bool {
	return context.RequestedIdentity != "" || context.SelectedDestinationAddress != "" || context.NetworkScope != "" || context.EffectiveRoute != "" || len(context.Provenance) > 0 || len(context.EvidenceIDs) > 0
}

func buildPathView(input pathInput) PathView {
	observation := input.observation
	evidenceIDs := append([]string(nil), input.provenance.EvidenceIDs...)
	pathView := PathView{
		EvidenceIDs:             evidenceIDs,
		Provenance:              observationProvenanceLabels(input.provenance),
		ProbeName:               input.provenance.ProbeName,
		Protocol:                observation.Protocol,
		ProtocolLabel:           labelForProtocol(observation.Protocol),
		ObservationStatus:       observation.Status,
		ObservationTone:         toneForPathStatus(observation.Status),
		ObservationLabel:        labelForPathStatus(observation.Status),
		Destination:             observation.Destination,
		DestinationPort:         observation.DestinationPort,
		PortAware:               observation.PortAware,
		DestinationReached:      observation.DestinationReached,
		DestinationTCPConnected: observation.DestinationTCPConnected,
		Hops:                    make([]PathHopView, 0, len(observation.Hops)),
		Segments:                make([]PathSegmentView, 0, len(observation.Segments)),
		Error:                   observation.Error,
	}
	if len(evidenceIDs) > 0 {
		pathView.EvidenceID = evidenceIDs[0]
	}
	for _, hop := range observation.Hops {
		hopView := PathHopView{
			TTL:         hop.TTL,
			State:       hop.State,
			Tone:        toneForHopState(hop.State),
			Label:       labelForHopState(hop.State),
			Detail:      detailForHopState(hop.State),
			Attempts:    hop.Attempts,
			Responders:  responderViews(hop.Responders),
			EvidenceIDs: append([]string(nil), evidenceIDs...),
		}
		pathView.Hops = append(pathView.Hops, hopView)
	}
	for _, segment := range observation.Segments {
		pathView.Segments = append(pathView.Segments, PathSegmentView{
			Kind:        segment.Kind,
			FromTTL:     segment.FromTTL,
			ToTTL:       segment.ToTTL,
			Tone:        toneForSegmentKind(segment.Kind),
			Label:       labelForSegmentKind(segment.Kind),
			Detail:      detailForSegmentKind(segment.Kind),
			Responders:  responderViews(segment.Responders),
			EvidenceIDs: append([]string(nil), evidenceIDs...),
		})
	}
	return pathView
}

func buildComparisons(correlations []model.PathCorrelation, inputs []pathInput) []ProtocolComparisonView {
	result := make([]ProtocolComparisonView, 0, len(correlations))
	for _, correlation := range correlations {
		comparison := ProtocolComparisonView{
			Destination:             correlation.Destination,
			DestinationPort:         correlation.DestinationPort,
			PortLabel:               portLabel(correlation.DestinationPort),
			Observations:            make([]ComparisonObservationView, 0, len(correlation.Observations)),
			ICMPDestinationReached:  correlation.ICMPDestinationReached,
			TCPDestinationReached:   correlation.TCPDestinationReached,
			TCPDestinationConnected: correlation.TCPDestinationConnected,
		}
		used := make([]bool, len(inputs))
		for _, observation := range correlation.Observations {
			inputIndex := matchingPathInput(inputs, used, observation)
			var provenance model.ObservationProvenance
			if inputIndex >= 0 {
				used[inputIndex] = true
				provenance = inputs[inputIndex].provenance
			}
			unobservable := make([]uint8, 0)
			responders := 0
			for _, hop := range observation.Hops {
				if hop.State == model.PathHopStateUnobservable {
					unobservable = append(unobservable, hop.TTL)
				}
				responders += len(hop.Responders)
			}
			evidence := append([]string(nil), provenance.EvidenceIDs...)
			comparison.Observations = append(comparison.Observations, ComparisonObservationView{
				EvidenceID: firstString(evidence), EvidenceIDs: evidence,
				Protocol: observation.Protocol, Status: observation.Status,
				PortAware: observation.PortAware, DestinationReached: observation.DestinationReached,
				DestinationTCPConnected: observation.DestinationTCPConnected,
				UnobservableTTLs:        unobservable, ResponderCount: responders,
			})
		}
		result = append(result, comparison)
	}
	return result
}

func matchingPathInput(inputs []pathInput, used []bool, observation model.PathObservation) int {
	for index, input := range inputs {
		if used[index] || input.observation.Destination != observation.Destination || input.observation.DestinationPort != observation.DestinationPort || input.observation.Protocol != observation.Protocol {
			continue
		}
		return index
	}
	return -1
}

func completedProgress(probes []ProbeView) []ProgressEvent {
	progress := make([]ProgressEvent, 0, len(probes)+1)
	progress = append(progress, ProgressEvent{State: "complete"})
	for _, probe := range probes {
		progress = append(progress, ProgressEvent{ProbeName: probe.Name, State: "complete", Status: probe.Status})
	}
	return progress
}

func responderViews(responders []model.PathResponder) []ResponderView {
	result := make([]ResponderView, 0, len(responders))
	for _, responder := range responders {
		result = append(result, ResponderView{
			Address:            responder.Address,
			RTTMS:              responder.RTTMS,
			Response:           responder.Response,
			DestinationReached: responder.DestinationReached,
		})
	}
	return result
}

func evidenceIDs(evidence []model.Evidence) []string {
	ids := make([]string, 0, len(evidence))
	for _, item := range evidence {
		ids = append(ids, item.ID)
	}
	return ids
}

func firstString(values []string) string {
	if len(values) == 0 {
		return ""
	}
	return values[0]
}

func observationProvenanceLabels(provenance model.ObservationProvenance) []string {
	labels := make([]string, 0, 2)
	if provenance.ProbeName != "" {
		labels = append(labels, "probe:"+provenance.ProbeName)
	}
	if provenance.Source != "" {
		labels = append(labels, "source:"+provenance.Source)
	}
	return labels
}

func isStructuredJSON(raw json.RawMessage) bool {
	trimmed := bytes.TrimSpace(raw)
	return len(trimmed) > 0 && (trimmed[0] == '{' || trimmed[0] == '[')
}

func toneForProbe(status model.ProbeStatus) string {
	switch status {
	case model.ProbeStatusPassed:
		return "positive"
	case model.ProbeStatusFailed, model.ProbeStatusError:
		return "negative"
	case model.ProbeStatusSkipped:
		return "warning"
	default:
		return "neutral"
	}
}

func toneForFailureReason(reason model.FailureReason) string {
	switch reason {
	case model.FailureReasonNone:
		return "positive"
	case model.FailureReasonUnsupported, model.FailureReasonICMPFailure, model.FailureReasonPathObservation, model.FailureReasonPathCancellation:
		return "warning"
	default:
		return "negative"
	}
}

func toneForPathStatus(status model.PathObservationStatus) string {
	switch status {
	case model.PathObservationStatusObserved:
		return "positive"
	case model.PathObservationStatusUnsupported:
		return "warning"
	case model.PathObservationStatusError:
		return "negative"
	default:
		return "neutral"
	}
}

func toneForHopState(state model.PathHopState) string {
	switch state {
	case model.PathHopStateObserved:
		return "positive"
	case model.PathHopStateUnobservable:
		return "neutral"
	default:
		return "warning"
	}
}

func toneForSegmentKind(kind model.PathSegmentKind) string {
	switch kind {
	case model.PathSegmentObservedResponder:
		return "positive"
	case model.PathSegmentUnobservable, model.PathSegmentInferred:
		return "neutral"
	default:
		return "warning"
	}
}

func labelForReportStatus(status model.ReportStatus) string {
	switch status {
	case model.ReportStatusComplete:
		return "Run complete"
	case model.ReportStatusIncomplete:
		return "Run incomplete"
	case model.ReportStatusError:
		return "Run error"
	default:
		return "Run state unknown"
	}
}

func labelForProbeStatus(status model.ProbeStatus) string {
	switch status {
	case model.ProbeStatusPassed:
		return "Passed"
	case model.ProbeStatusFailed:
		return "Failed"
	case model.ProbeStatusError:
		return "Error"
	case model.ProbeStatusSkipped:
		return "Skipped / unsupported"
	default:
		return "Unknown"
	}
}

func labelForFailureReason(reason model.FailureReason) string {
	if reason == model.FailureReasonNone {
		return "No failure"
	}
	words := strings.Split(string(reason), "_")
	for index, word := range words {
		if word == "" {
			continue
		}
		words[index] = strings.ToUpper(word[:1]) + word[1:]
	}
	return strings.Join(words, " ")
}

func labelForProtocol(protocol model.PathProtocol) string {
	switch protocol {
	case model.PathProtocolICMP:
		return "ICMP"
	case model.PathProtocolTCP:
		return "TCP"
	case model.PathProtocolUDP:
		return "UDP"
	default:
		return "Unknown protocol"
	}
}

func labelForPathStatus(status model.PathObservationStatus) string {
	switch status {
	case model.PathObservationStatusObserved:
		return "Observed"
	case model.PathObservationStatusUnsupported:
		return "Unsupported"
	case model.PathObservationStatusError:
		return "Error"
	default:
		return "Unknown"
	}
}

func labelForHopState(state model.PathHopState) string {
	switch state {
	case model.PathHopStateObserved:
		return "Observed responder"
	case model.PathHopStateUnobservable:
		return "Unobservable"
	default:
		return "Unknown"
	}
}

func detailForHopState(state model.PathHopState) string {
	switch state {
	case model.PathHopStateObserved:
		return "A responder was observed at this TTL."
	case model.PathHopStateUnobservable:
		return "No responder was observed at this TTL; this is not packet loss."
	default:
		return "The observation state is not known."
	}
}

func labelForSegmentKind(kind model.PathSegmentKind) string {
	switch kind {
	case model.PathSegmentObservedResponder:
		return "Observed responder"
	case model.PathSegmentInferred:
		return "Inferred transit range"
	case model.PathSegmentUnobservable:
		return "Unobservable range"
	default:
		return "Unknown segment"
	}
}

func detailForSegmentKind(kind model.PathSegmentKind) string {
	switch kind {
	case model.PathSegmentObservedResponder:
		return "Direct responder evidence for this TTL."
	case model.PathSegmentInferred:
		return "Bounded inference between observations; not an exact physical link."
	case model.PathSegmentUnobservable:
		return "No responder was observed in this TTL range; this is not packet loss."
	default:
		return "The segment type is not known."
	}
}

func portLabel(port uint16) string {
	if port == 0 {
		return "destination port unspecified"
	}
	return fmt.Sprintf("destination port %d", port)
}

func pluralSuffix(count int) string {
	if count == 1 {
		return ""
	}
	return "s"
}

func uniqueStrings(values []string) []string {
	if len(values) < 2 {
		return values
	}
	seen := make(map[string]struct{}, len(values))
	result := make([]string, 0, len(values))
	for _, value := range values {
		if _, ok := seen[value]; ok {
			continue
		}
		seen[value] = struct{}{}
		result = append(result, value)
	}
	return result
}
