package web

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/yohnark/tadori/internal/model"
	"github.com/yohnark/tadori/internal/report"
)

// ProgressEvent is the deliberately small, UI-owned event shape used by the
// view endpoint. It is not a runtime/session contract. A future session or
// SSE adapter can translate its events into this shape without changing the
// canonical diagnostic model or the view renderer.
type ProgressEvent struct {
	ProbeName string            `json:"probe_name,omitempty"`
	State     string            `json:"state"`
	Status    model.ProbeStatus `json:"status,omitempty"`
}

// ProgressRunner is an optional adapter for a runner that can report
// presentation progress on the legacy synchronous view endpoint. The
// session/SSE runtime has its own published contract and is used by the
// browser's normal workflow; this adapter remains useful to embedders and
// deterministic tests without coupling them to session storage.
type ProgressRunner func(context.Context, model.Target, func(ProgressEvent)) model.DiagnosticReport

// DiagnosticViewModel is an additive presentation projection. Report is the
// canonical source of truth; every other field is derived from it and can be
// discarded and rebuilt. CanonicalJSON is generated by report.MarshalJSON so
// the inspector does not re-serialize or reinterpret raw evidence in the
// browser.
type DiagnosticViewModel struct {
	Report         model.DiagnosticReport   `json:"report"`
	CanonicalJSON  string                   `json:"canonical_json"`
	NetworkContext *NetworkContextView      `json:"network_context,omitempty"`
	Overall        OverallView              `json:"overall"`
	Progress       []ProgressEvent          `json:"progress"`
	Probes         []ProbeView              `json:"probes"`
	Findings       []FindingView            `json:"findings"`
	Evidence       []EvidenceView           `json:"evidence"`
	Paths          []PathView               `json:"paths"`
	Comparisons    []ProtocolComparisonView `json:"comparisons"`
}

// NetworkContextView is the presentation projection of the canonical target
// routing context. The machine-readable context remains in Report.Target;
// labels here are derived only for the browser view.
type NetworkContextView struct {
	NetworkScope               model.NetworkScope      `json:"network_scope"`
	NetworkScopeLabel          string                  `json:"network_scope_label"`
	RequestedIdentity          string                  `json:"requested_identity"`
	SelectedDestinationAddress string                  `json:"selected_destination_address,omitempty"`
	SelectedSourceInterface    string                  `json:"selected_source_interface,omitempty"`
	SelectedSourceAddress      string                  `json:"selected_source_address,omitempty"`
	EffectiveRoute             model.RouteDisposition  `json:"effective_route"`
	EffectiveRouteLabel        string                  `json:"effective_route_label"`
	RoutePrefix                string                  `json:"route_prefix,omitempty"`
	NextHop                    string                  `json:"next_hop,omitempty"`
	Gateway                    string                  `json:"gateway,omitempty"`
	RouteMetric                int                     `json:"route_metric"`
	VPNOrTunnelInvolvement     bool                    `json:"vpn_or_tunnel_involvement,omitempty"`
	VirtualAdapterInvolvement  bool                    `json:"virtual_adapter_involvement,omitempty"`
	RouteSelectionAmbiguous    bool                    `json:"route_selection_ambiguous,omitempty"`
	CompetingRoutes            []model.RouteCandidate  `json:"competing_routes,omitempty"`
	Neighbor                   *model.NeighborEvidence `json:"neighbor,omitempty"`
	Provenance                 []string                `json:"provenance,omitempty"`
	EvidenceIDs                []string                `json:"evidence_ids,omitempty"`
}

// OverallView keeps report execution status separate from diagnosis and from
// destination reachability. In particular, a complete report can still have
// a failed destination or a destination confirmed while intermediate hops
// are unobservable.
type OverallView struct {
	ExecutionStatus model.ReportStatus `json:"execution_status"`
	ExecutionLabel  string             `json:"execution_label"`
	DiagnosisState  string             `json:"diagnosis_state"`
	DiagnosisLabel  string             `json:"diagnosis_label"`
	Tone            string             `json:"tone"`
	Destination     DestinationView    `json:"destination"`
}

// DestinationView describes only endpoint evidence. It intentionally does
// not use the observability of intermediate path hops as a proxy for endpoint
// reachability.
type DestinationView struct {
	State       string   `json:"state"`
	Label       string   `json:"label"`
	Detail      string   `json:"detail"`
	ProbeNames  []string `json:"probe_names,omitempty"`
	EvidenceIDs []string `json:"evidence_ids,omitempty"`
}

type ProbeView struct {
	Name          string              `json:"name"`
	Status        model.ProbeStatus   `json:"status"`
	Tone          string              `json:"tone"`
	StatusLabel   string              `json:"status_label"`
	DurationMS    int64               `json:"duration_ms"`
	FailureReason model.FailureReason `json:"failure_reason"`
	Layer         model.Layer         `json:"layer"`
	FaultDomain   model.FaultDomain   `json:"fault_domain"`
	EvidenceIDs   []string            `json:"evidence_ids,omitempty"`
}

type FindingView struct {
	FailureReason model.FailureReason `json:"failure_reason"`
	Label         string              `json:"label"`
	Tone          string              `json:"tone"`
	Layer         model.Layer         `json:"layer"`
	FaultDomain   model.FaultDomain   `json:"fault_domain"`
	ProbeNames    []string            `json:"probe_names,omitempty"`
	EvidenceIDs   []string            `json:"evidence_ids,omitempty"`
}

type EvidenceView struct {
	ID             string             `json:"id"`
	ProbeName      string             `json:"probe_name"`
	Kind           model.EvidenceKind `json:"kind"`
	Source         string             `json:"source,omitempty"`
	CapturedAt     *time.Time         `json:"captured_at,omitempty"`
	Structured     bool               `json:"structured"`
	InspectorState string             `json:"inspector_state"`
	InspectorNote  string             `json:"inspector_note,omitempty"`
	Raw            json.RawMessage    `json:"raw"`
}

type PathView struct {
	EvidenceID              string                      `json:"evidence_id"`
	ProbeName               string                      `json:"probe_name"`
	Protocol                model.PathProtocol          `json:"protocol"`
	ProtocolLabel           string                      `json:"protocol_label"`
	ObservationStatus       model.PathObservationStatus `json:"observation_status"`
	ObservationTone         string                      `json:"observation_tone"`
	ObservationLabel        string                      `json:"observation_label"`
	Destination             string                      `json:"destination"`
	DestinationPort         uint16                      `json:"destination_port"`
	PortAware               bool                        `json:"port_aware"`
	DestinationReached      bool                        `json:"destination_reached"`
	DestinationTCPConnected bool                        `json:"destination_tcp_connected"`
	DestinationState        string                      `json:"destination_state"`
	DestinationLabel        string                      `json:"destination_label"`
	DestinationDetail       string                      `json:"destination_detail"`
	Hops                    []PathHopView               `json:"hops"`
	Segments                []PathSegmentView           `json:"segments"`
	Error                   string                      `json:"error,omitempty"`
}

type PathHopView struct {
	TTL         uint8              `json:"ttl"`
	State       model.PathHopState `json:"state"`
	Tone        string             `json:"tone"`
	Label       string             `json:"label"`
	Detail      string             `json:"detail"`
	Attempts    int                `json:"attempts,omitempty"`
	Responders  []ResponderView    `json:"responders"`
	EvidenceIDs []string           `json:"evidence_ids,omitempty"`
}

type ResponderView struct {
	Address            string `json:"address"`
	RTTMS              int64  `json:"rtt_ms,omitempty"`
	Response           string `json:"response,omitempty"`
	DestinationReached bool   `json:"destination_reached,omitempty"`
}

type PathSegmentView struct {
	Kind        model.PathSegmentKind `json:"kind"`
	FromTTL     uint8                 `json:"from_ttl"`
	ToTTL       uint8                 `json:"to_ttl"`
	Tone        string                `json:"tone"`
	Label       string                `json:"label"`
	Detail      string                `json:"detail"`
	Responders  []ResponderView       `json:"responders"`
	EvidenceIDs []string              `json:"evidence_ids,omitempty"`
}

type ProtocolComparisonView struct {
	Destination             string                      `json:"destination"`
	DestinationPort         uint16                      `json:"destination_port"`
	PortLabel               string                      `json:"port_label"`
	Observations            []ComparisonObservationView `json:"observations"`
	ICMPDestinationReached  bool                        `json:"icmp_destination_reached"`
	TCPDestinationReached   bool                        `json:"tcp_destination_reached"`
	TCPDestinationConnected bool                        `json:"tcp_destination_connected"`
}

type ComparisonObservationView struct {
	EvidenceID              string                      `json:"evidence_id"`
	Protocol                model.PathProtocol          `json:"protocol"`
	Status                  model.PathObservationStatus `json:"status"`
	PortAware               bool                        `json:"port_aware"`
	DestinationReached      bool                        `json:"destination_reached"`
	DestinationTCPConnected bool                        `json:"destination_tcp_connected"`
	DestinationState        string                      `json:"destination_state"`
	DestinationLabel        string                      `json:"destination_label"`
	UnobservableTTLs        []uint8                     `json:"unobservable_ttls,omitempty"`
	ResponderCount          int                         `json:"responder_count"`
}

// BuildDiagnosticView builds the UI projection from one canonical report.
// It never runs probes, changes the report, or parses raw evidence except for
// the known path-observation shape. Unknown evidence remains available in the
// inspector as raw JSON.
func BuildDiagnosticView(diagnosticReport model.DiagnosticReport) (DiagnosticViewModel, error) {
	canonical, err := report.MarshalJSON(diagnosticReport)
	if err != nil {
		return DiagnosticViewModel{}, fmt.Errorf("marshal canonical report for UI: %w", err)
	}

	view := DiagnosticViewModel{
		Report:        diagnosticReport,
		CanonicalJSON: string(canonical),
		Progress:      make([]ProgressEvent, 0),
		Probes:        make([]ProbeView, 0, len(diagnosticReport.Probes)),
		Findings:      make([]FindingView, 0, len(diagnosticReport.Findings)),
		Evidence:      make([]EvidenceView, 0),
		Paths:         make([]PathView, 0),
		Comparisons:   make([]ProtocolComparisonView, 0),
	}
	if diagnosticReport.Target.NetworkContext != nil {
		view.NetworkContext = buildNetworkContextView(*diagnosticReport.Target.NetworkContext)
	}

	view.Overall = buildOverallView(diagnosticReport)
	pathInputs := make([]pathInput, 0)
	for _, probe := range diagnosticReport.Probes {
		probeEvidenceIDs := evidenceIDs(probe.Evidence)
		view.Probes = append(view.Probes, ProbeView{
			Name:          probe.Name,
			Status:        probe.Status,
			Tone:          toneForProbe(probe.Status),
			StatusLabel:   labelForProbeStatus(probe.Status),
			DurationMS:    probe.Timing.DurationMS,
			FailureReason: probe.Interpretation.FailureReason,
			Layer:         probe.Interpretation.Layer,
			FaultDomain:   probe.Interpretation.FaultDomain,
			EvidenceIDs:   probeEvidenceIDs,
		})
		for _, evidence := range probe.Evidence {
			evidenceView := EvidenceView{
				ID:             evidence.ID,
				ProbeName:      probe.Name,
				Kind:           evidence.Kind,
				Source:         evidence.Source,
				CapturedAt:     evidence.CapturedAt,
				Structured:     isStructuredJSON(evidence.Raw),
				InspectorState: "available",
				Raw:            evidence.Raw,
			}
			if evidence.Kind == model.EvidenceKindPathObservation {
				observation, decodeErr := model.DecodePathObservation(evidence)
				if decodeErr != nil {
					evidenceView.InspectorState = "partial"
					evidenceView.InspectorNote = "Path view is unavailable; the original path evidence is retained below."
				} else {
					pathInputs = append(pathInputs, pathInput{probeName: probe.Name, evidenceID: evidence.ID, observation: observation})
				}
			}
			view.Evidence = append(view.Evidence, evidenceView)
		}
	}

	for _, finding := range diagnosticReport.Findings {
		view.Findings = append(view.Findings, FindingView{
			FailureReason: finding.FailureReason,
			Label:         labelForFailureReason(finding.FailureReason),
			Tone:          toneForFailureReason(finding.FailureReason),
			Layer:         finding.Layer,
			FaultDomain:   finding.FaultDomain,
			ProbeNames:    append([]string(nil), finding.ProbeNames...),
			EvidenceIDs:   append([]string(nil), finding.EvidenceIDs...),
		})
	}

	for _, input := range pathInputs {
		view.Paths = append(view.Paths, buildPathView(input))
	}
	view.Comparisons = buildComparisons(pathInputs)
	view.Progress = completedProgress(view.Probes)
	return view, nil
}

func buildNetworkContextView(context model.NetworkContext) *NetworkContextView {
	return &NetworkContextView{
		NetworkScope:               context.NetworkScope,
		NetworkScopeLabel:          networkScopeLabel(context.NetworkScope),
		RequestedIdentity:          context.RequestedIdentity,
		SelectedDestinationAddress: context.SelectedDestinationAddress,
		SelectedSourceInterface:    context.SelectedSourceInterface,
		SelectedSourceAddress:      context.SelectedSourceAddress,
		EffectiveRoute:             context.EffectiveRoute,
		EffectiveRouteLabel:        routeDispositionLabel(context.EffectiveRoute),
		RoutePrefix:                context.RoutePrefix,
		NextHop:                    context.NextHop,
		Gateway:                    context.Gateway,
		RouteMetric:                context.RouteMetric,
		VPNOrTunnelInvolvement:     context.VPNOrTunnelInvolvement,
		VirtualAdapterInvolvement:  context.VirtualAdapterInvolvement,
		RouteSelectionAmbiguous:    context.RouteSelectionAmbiguous,
		CompetingRoutes:            append([]model.RouteCandidate(nil), context.CompetingRoutes...),
		Neighbor:                   cloneNeighborEvidence(context.Neighbor),
		Provenance:                 append([]string(nil), context.Provenance...),
		EvidenceIDs:                append([]string(nil), context.EvidenceIDs...),
	}
}

func cloneNeighborEvidence(neighbor *model.NeighborEvidence) *model.NeighborEvidence {
	if neighbor == nil {
		return nil
	}
	copy := *neighbor
	copy.Entries = append([]model.NeighborEntry(nil), neighbor.Entries...)
	return &copy
}

func networkScopeLabel(scope model.NetworkScope) string {
	switch scope {
	case model.NetworkScopeLoopback:
		return "Loopback"
	case model.NetworkScopeLinkLocal:
		return "Link-local"
	case model.NetworkScopeSameLink:
		return "Local link"
	case model.NetworkScopePrivateRouted:
		return "Private routed"
	case model.NetworkScopeVPNTunnelRouted:
		return "VPN / tunnel routed"
	case model.NetworkScopeExternalRouted:
		return "External routed"
	default:
		return "Unknown"
	}
}

func routeDispositionLabel(disposition model.RouteDisposition) string {
	switch disposition {
	case model.RouteDispositionOnLink:
		return "On-link"
	case model.RouteDispositionRouted:
		return "Routed"
	default:
		return "Unknown"
	}
}

type pathInput struct {
	probeName   string
	evidenceID  string
	observation model.PathObservation
}

func buildOverallView(diagnosticReport model.DiagnosticReport) OverallView {
	diagnosisState := "clear"
	diagnosisLabel := "No canonical findings"
	tone := "positive"
	if len(diagnosticReport.Findings) > 0 {
		diagnosisState = "finding"
		diagnosisLabel = fmt.Sprintf("%d canonical finding%s", len(diagnosticReport.Findings), pluralSuffix(len(diagnosticReport.Findings)))
		tone = "negative"
	} else if diagnosticReport.Status == model.ReportStatusIncomplete {
		diagnosisState = "incomplete"
		diagnosisLabel = "Evidence is incomplete"
		tone = "warning"
	} else if diagnosticReport.Status == model.ReportStatusError || diagnosticReport.Status == model.ReportStatusUnknown {
		diagnosisState = "unknown"
		diagnosisLabel = "Diagnosis is unavailable"
		tone = "neutral"
	}

	return OverallView{
		ExecutionStatus: diagnosticReport.Status,
		ExecutionLabel:  labelForReportStatus(diagnosticReport.Status),
		DiagnosisState:  diagnosisState,
		DiagnosisLabel:  diagnosisLabel,
		Tone:            tone,
		Destination:     destinationView(diagnosticReport),
	}
}

func destinationView(diagnosticReport model.DiagnosticReport) DestinationView {
	confirmed := make([]string, 0)
	reachedButNotConnected := make([]string, 0)
	failed := make([]string, 0)
	unknownEvidence := false
	for _, probe := range diagnosticReport.Probes {
		if probeMatchesTarget(probe, diagnosticReport.Target) && !hasPathEvidence(probe) && probe.Status == model.ProbeStatusPassed && probe.Interpretation.FailureReason == model.FailureReasonNone &&
			(probe.Interpretation.Layer == model.LayerTCP || probe.Interpretation.Layer == model.LayerTLS || probe.Interpretation.Layer == model.LayerHTTP) {
			confirmed = append(confirmed, probe.Name)
		}
		if probeMatchesTarget(probe, diagnosticReport.Target) && probe.Interpretation.Layer == model.LayerTCP && probe.Status != model.ProbeStatusSkipped {
			if probe.Status == model.ProbeStatusFailed || probe.Status == model.ProbeStatusError {
				failed = append(failed, probe.Name)
			}
		}
		for _, evidence := range probe.Evidence {
			if evidence.Kind == model.EvidenceKindPacketFlow {
				if flow, ok := packetFlowForTarget(evidence, diagnosticReport.Target); ok {
					switch flow.Outcome {
					case model.PacketFlowOutcomeTCPHandshakeConfirmed, model.PacketFlowOutcomeTCPSYNACK:
						confirmed = append(confirmed, probe.Name)
					case model.PacketFlowOutcomeTCPRST:
						reachedButNotConnected = append(reachedButNotConnected, probe.Name)
					}
				}
			}
			if evidence.Kind != model.EvidenceKindPathObservation {
				continue
			}
			observation, err := model.DecodePathObservation(evidence)
			if err != nil {
				unknownEvidence = true
				continue
			}
			if !pathObservationForTarget(observation, diagnosticReport.Target) {
				continue
			}
			if observation.Protocol == model.PathProtocolTCP && observation.PortAware {
				if observation.DestinationReached && observation.DestinationTCPConnected {
					confirmed = append(confirmed, probe.Name)
				} else if observation.DestinationReached {
					reachedButNotConnected = append(reachedButNotConnected, probe.Name)
				} else if observation.Status == model.PathObservationStatusObserved {
					failed = append(failed, probe.Name)
				}
			}
		}
	}

	if len(confirmed) > 0 {
		return DestinationView{
			State:       "confirmed",
			Label:       "Destination confirmed",
			Detail:      "A transport or application observation reached the requested endpoint.",
			ProbeNames:  uniqueStrings(confirmed),
			EvidenceIDs: destinationEvidenceIDs(diagnosticReport, "confirmed"),
		}
	}
	if len(reachedButNotConnected) > 0 {
		return DestinationView{
			State:       "reached_not_connected",
			Label:       "Destination reached; port not connected",
			Detail:      "The destination responded to a TCP path observation, but the requested port did not establish a connection.",
			ProbeNames:  uniqueStrings(reachedButNotConnected),
			EvidenceIDs: destinationEvidenceIDs(diagnosticReport, "reached_not_connected"),
		}
	}
	if len(failed) > 0 {
		return DestinationView{
			State:       "failed",
			Label:       "Destination connectivity failed",
			Detail:      "The requested transport endpoint produced a canonical failure result.",
			ProbeNames:  uniqueStrings(failed),
			EvidenceIDs: destinationEvidenceIDs(diagnosticReport, "failed"),
		}
	}
	if unknownEvidence || len(diagnosticReport.Probes) == 0 {
		return DestinationView{State: "unknown", Label: "Destination state unknown", Detail: "No usable endpoint evidence is available."}
	}
	return DestinationView{State: "unconfirmed", Label: "Destination not confirmed", Detail: "Intermediate observations do not establish requested endpoint connectivity."}
}

func destinationEvidenceIDs(diagnosticReport model.DiagnosticReport, state string) []string {
	ids := make([]string, 0)
	for _, probe := range diagnosticReport.Probes {
		if state == "confirmed" && probeMatchesTarget(probe, diagnosticReport.Target) && !hasPathEvidence(probe) && probe.Status == model.ProbeStatusPassed && probe.Interpretation.FailureReason == model.FailureReasonNone &&
			(probe.Interpretation.Layer == model.LayerTCP || probe.Interpretation.Layer == model.LayerTLS || probe.Interpretation.Layer == model.LayerHTTP) {
			ids = append(ids, evidenceIDs(probe.Evidence)...)
		}
		if state == "failed" && probeMatchesTarget(probe, diagnosticReport.Target) && probe.Interpretation.Layer == model.LayerTCP && (probe.Status == model.ProbeStatusFailed || probe.Status == model.ProbeStatusError) {
			ids = append(ids, evidenceIDs(probe.Evidence)...)
		}
		if (state == "confirmed" || state == "failed") && probeMatchesTarget(probe, diagnosticReport.Target) {
			for _, evidence := range probe.Evidence {
				if state == "confirmed" {
					if flow, ok := packetFlowForTarget(evidence, diagnosticReport.Target); ok && (flow.Outcome == model.PacketFlowOutcomeTCPHandshakeConfirmed || flow.Outcome == model.PacketFlowOutcomeTCPSYNACK) {
						ids = append(ids, evidence.ID)
					}
				}
				if evidence.Kind != model.EvidenceKindPathObservation {
					continue
				}
				observation, err := model.DecodePathObservation(evidence)
				if err != nil || !pathObservationForTarget(observation, diagnosticReport.Target) || observation.Protocol != model.PathProtocolTCP || !observation.PortAware {
					continue
				}
				if state == "confirmed" && observation.DestinationReached && observation.DestinationTCPConnected {
					ids = append(ids, evidence.ID)
				}
				if state == "failed" && observation.Status == model.PathObservationStatusObserved && !observation.DestinationReached {
					ids = append(ids, evidence.ID)
				}
			}
		}
		if state == "reached_not_connected" && probeMatchesTarget(probe, diagnosticReport.Target) {
			for _, evidence := range probe.Evidence {
				if flow, ok := packetFlowForTarget(evidence, diagnosticReport.Target); ok && flow.Outcome == model.PacketFlowOutcomeTCPRST {
					ids = append(ids, evidence.ID)
				}
				if evidence.Kind != model.EvidenceKindPathObservation {
					continue
				}
				if observation, err := model.DecodePathObservation(evidence); err == nil && pathObservationForTarget(observation, diagnosticReport.Target) && observation.Protocol == model.PathProtocolTCP && observation.DestinationReached && !observation.DestinationTCPConnected {
					ids = append(ids, evidence.ID)
				}
			}
		}
	}
	return uniqueStrings(ids)
}

func packetFlowForTarget(evidence model.Evidence, target model.Target) (model.PacketFlowEvidence, bool) {
	if evidence.Kind != model.EvidenceKindPacketFlow {
		return model.PacketFlowEvidence{}, false
	}
	flow, err := model.DecodePacketFlowEvidence(evidence)
	if err != nil || flow.CaptureStatus != model.PacketCaptureStatusAvailable {
		return model.PacketFlowEvidence{}, false
	}
	if (flow.Outcome == model.PacketFlowOutcomeTCPHandshakeConfirmed || flow.Outcome == model.PacketFlowOutcomeTCPSYNACK || flow.Outcome == model.PacketFlowOutcomeTCPRST) && flow.Certainty != model.EvidenceCertaintyConfirmedEndpointResponse {
		return model.PacketFlowEvidence{}, false
	}
	if target.Port != 0 && flow.Target.Port != 0 && target.Port != flow.Target.Port {
		return model.PacketFlowEvidence{}, false
	}
	if target.RequestedIdentity != "" && flow.Target.RequestedIdentity != "" &&
		!target.MatchesAddress(flow.Target.RequestedIdentity) && !flow.Target.MatchesAddress(target.RequestedIdentity) {
		return model.PacketFlowEvidence{}, false
	}
	return flow, true
}

func pathObservationForTarget(observation model.PathObservation, target model.Target) bool {
	if observation.DestinationPort != target.Port || target.Port == 0 {
		return false
	}
	// A hostname is resolved by the path adapter, so its observed destination
	// is expected to be an address rather than the original hostname. Literal
	// targets can be matched exactly through the canonical model helper.
	return observation.MatchesTarget(target)
}

func probeMatchesTarget(probe model.ProbeResult, target model.Target) bool {
	if target.Port != 0 && probe.Target.Port != 0 && target.Port != probe.Target.Port {
		return false
	}
	if target.RequestedIdentity == "" || probe.Target.RequestedIdentity == "" {
		return true
	}
	if target.MatchesAddress(probe.Target.RequestedIdentity) || probe.Target.MatchesAddress(target.RequestedIdentity) {
		return true
	}
	return false
}

func hasPathEvidence(probe model.ProbeResult) bool {
	for _, evidence := range probe.Evidence {
		if evidence.Kind == model.EvidenceKindPathObservation {
			return true
		}
	}
	return false
}

func buildPathView(input pathInput) PathView {
	observation := input.observation
	pathView := PathView{
		EvidenceID:              input.evidenceID,
		ProbeName:               input.probeName,
		Protocol:                observation.Protocol,
		ProtocolLabel:           labelForProtocol(observation.Protocol),
		ObservationStatus:       observation.Status,
		ObservationTone:         toneForPathStatus(observation.Status),
		ObservationLabel:        labelForPathStatus(observation.Status),
		Destination:             observation.Destination,
		DestinationPort:         observation.DestinationPort,
		PortAware:               observation.PortAware,
		DestinationReached:      observation.DestinationReached,
		DestinationTCPConnected: observation.DestinationTCPConnected,
		Hops:                    make([]PathHopView, 0, len(observation.Hops)),
		Segments:                make([]PathSegmentView, 0, len(observation.Segments)),
		Error:                   observation.Error,
	}
	pathView.DestinationState, pathView.DestinationLabel, pathView.DestinationDetail = pathDestinationState(observation)
	for _, hop := range observation.Hops {
		hopView := PathHopView{
			TTL:         hop.TTL,
			State:       hop.State,
			Tone:        toneForHopState(hop.State),
			Label:       labelForHopState(hop.State),
			Detail:      detailForHopState(hop.State),
			Attempts:    hop.Attempts,
			Responders:  responderViews(hop.Responders),
			EvidenceIDs: []string{input.evidenceID},
		}
		pathView.Hops = append(pathView.Hops, hopView)
	}
	for _, segment := range observation.Segments {
		pathView.Segments = append(pathView.Segments, PathSegmentView{
			Kind:        segment.Kind,
			FromTTL:     segment.FromTTL,
			ToTTL:       segment.ToTTL,
			Tone:        toneForSegmentKind(segment.Kind),
			Label:       labelForSegmentKind(segment.Kind),
			Detail:      detailForSegmentKind(segment.Kind),
			Responders:  responderViews(segment.Responders),
			EvidenceIDs: []string{input.evidenceID},
		})
	}
	return pathView
}

func buildComparisons(inputs []pathInput) []ProtocolComparisonView {
	type group struct {
		destination string
		port        uint16
		inputs      []pathInput
	}
	groups := make(map[string]*group)
	for _, input := range inputs {
		key := input.observation.Destination + "\x00" + fmt.Sprint(input.observation.DestinationPort)
		if groups[key] == nil {
			groups[key] = &group{destination: input.observation.Destination, port: input.observation.DestinationPort}
		}
		groups[key].inputs = append(groups[key].inputs, input)
	}
	result := make([]ProtocolComparisonView, 0, len(groups))
	for _, value := range groups {
		observations := make([]model.PathObservation, 0, len(value.inputs))
		for _, input := range value.inputs {
			observations = append(observations, input.observation)
		}
		correlations := model.CorrelatePathObservations(observations...)
		comparison := ProtocolComparisonView{
			Destination:     value.destination,
			DestinationPort: value.port,
			PortLabel:       portLabel(value.port),
			Observations:    make([]ComparisonObservationView, 0, len(value.inputs)),
		}
		if len(correlations) == 1 {
			comparison.ICMPDestinationReached = correlations[0].ICMPDestinationReached
			comparison.TCPDestinationReached = correlations[0].TCPDestinationReached
			comparison.TCPDestinationConnected = correlations[0].TCPDestinationConnected
		}
		for _, input := range value.inputs {
			unobservable := make([]uint8, 0)
			responders := 0
			for _, hop := range input.observation.Hops {
				if hop.State == model.PathHopStateUnobservable {
					unobservable = append(unobservable, hop.TTL)
				}
				responders += len(hop.Responders)
			}
			state, label, _ := pathDestinationState(input.observation)
			comparison.Observations = append(comparison.Observations, ComparisonObservationView{
				EvidenceID:              input.evidenceID,
				Protocol:                input.observation.Protocol,
				Status:                  input.observation.Status,
				PortAware:               input.observation.PortAware,
				DestinationReached:      input.observation.DestinationReached,
				DestinationTCPConnected: input.observation.DestinationTCPConnected,
				DestinationState:        state,
				DestinationLabel:        label,
				UnobservableTTLs:        unobservable,
				ResponderCount:          responders,
			})
		}
		sort.SliceStable(comparison.Observations, func(i, j int) bool {
			return comparison.Observations[i].Protocol < comparison.Observations[j].Protocol
		})
		result = append(result, comparison)
	}
	sort.SliceStable(result, func(i, j int) bool {
		if result[i].Destination != result[j].Destination {
			return result[i].Destination < result[j].Destination
		}
		return result[i].DestinationPort < result[j].DestinationPort
	})
	return result
}

func pathDestinationState(observation model.PathObservation) (string, string, string) {
	switch {
	case observation.Status == model.PathObservationStatusUnsupported:
		return "unsupported", "Path capability unsupported", "This protocol could not produce a path observation on this runtime."
	case observation.Status == model.PathObservationStatusError:
		return "error", "Path observation failed", "The path adapter returned an error; this is distinct from an unobservable TTL."
	case observation.Protocol == model.PathProtocolTCP && observation.PortAware && observation.DestinationReached && observation.DestinationTCPConnected:
		return "confirmed", "Destination confirmed", "TCP connected at the requested destination port."
	case observation.Protocol == model.PathProtocolTCP && observation.PortAware && observation.DestinationReached:
		return "reached_not_connected", "Destination reached; port not connected", "The destination answered, but this TCP port did not establish a connection."
	case observation.Protocol == model.PathProtocolICMP && observation.DestinationReached:
		return "icmp_replied", "ICMP destination replied", "ICMP reachability does not prove transport or application connectivity."
	case observation.Status == model.PathObservationStatusObserved:
		return "not_reached", "Destination not reached", "No destination response was observed by this protocol."
	default:
		return "unknown", "Destination state unknown", "The observation does not establish destination reachability."
	}
}

func completedProgress(probes []ProbeView) []ProgressEvent {
	progress := make([]ProgressEvent, 0, len(probes)+1)
	progress = append(progress, ProgressEvent{State: "complete"})
	for _, probe := range probes {
		progress = append(progress, ProgressEvent{ProbeName: probe.Name, State: "complete", Status: probe.Status})
	}
	return progress
}

func responderViews(responders []model.PathResponder) []ResponderView {
	result := make([]ResponderView, 0, len(responders))
	for _, responder := range responders {
		result = append(result, ResponderView{
			Address:            responder.Address,
			RTTMS:              responder.RTTMS,
			Response:           responder.Response,
			DestinationReached: responder.DestinationReached,
		})
	}
	return result
}

func evidenceIDs(evidence []model.Evidence) []string {
	ids := make([]string, 0, len(evidence))
	for _, item := range evidence {
		ids = append(ids, item.ID)
	}
	return ids
}

func isStructuredJSON(raw json.RawMessage) bool {
	trimmed := bytes.TrimSpace(raw)
	return len(trimmed) > 0 && (trimmed[0] == '{' || trimmed[0] == '[')
}

func toneForProbe(status model.ProbeStatus) string {
	switch status {
	case model.ProbeStatusPassed:
		return "positive"
	case model.ProbeStatusFailed, model.ProbeStatusError:
		return "negative"
	case model.ProbeStatusSkipped:
		return "warning"
	default:
		return "neutral"
	}
}

func toneForFailureReason(reason model.FailureReason) string {
	switch reason {
	case model.FailureReasonNone:
		return "positive"
	case model.FailureReasonUnsupported, model.FailureReasonICMPFailure, model.FailureReasonPathObservation, model.FailureReasonPathCancellation:
		return "warning"
	default:
		return "negative"
	}
}

func toneForPathStatus(status model.PathObservationStatus) string {
	switch status {
	case model.PathObservationStatusObserved:
		return "positive"
	case model.PathObservationStatusUnsupported:
		return "warning"
	case model.PathObservationStatusError:
		return "negative"
	default:
		return "neutral"
	}
}

func toneForHopState(state model.PathHopState) string {
	switch state {
	case model.PathHopStateObserved:
		return "positive"
	case model.PathHopStateUnobservable:
		return "neutral"
	default:
		return "warning"
	}
}

func toneForSegmentKind(kind model.PathSegmentKind) string {
	switch kind {
	case model.PathSegmentObservedResponder:
		return "positive"
	case model.PathSegmentUnobservable, model.PathSegmentInferred:
		return "neutral"
	default:
		return "warning"
	}
}

func labelForReportStatus(status model.ReportStatus) string {
	switch status {
	case model.ReportStatusComplete:
		return "Run complete"
	case model.ReportStatusIncomplete:
		return "Run incomplete"
	case model.ReportStatusError:
		return "Run error"
	default:
		return "Run state unknown"
	}
}

func labelForProbeStatus(status model.ProbeStatus) string {
	switch status {
	case model.ProbeStatusPassed:
		return "Passed"
	case model.ProbeStatusFailed:
		return "Failed"
	case model.ProbeStatusError:
		return "Error"
	case model.ProbeStatusSkipped:
		return "Skipped / unsupported"
	default:
		return "Unknown"
	}
}

func labelForFailureReason(reason model.FailureReason) string {
	if reason == model.FailureReasonNone {
		return "No failure"
	}
	words := strings.Split(string(reason), "_")
	for index, word := range words {
		if word == "" {
			continue
		}
		words[index] = strings.ToUpper(word[:1]) + word[1:]
	}
	return strings.Join(words, " ")
}

func labelForProtocol(protocol model.PathProtocol) string {
	switch protocol {
	case model.PathProtocolICMP:
		return "ICMP"
	case model.PathProtocolTCP:
		return "TCP"
	case model.PathProtocolUDP:
		return "UDP"
	default:
		return "Unknown protocol"
	}
}

func labelForPathStatus(status model.PathObservationStatus) string {
	switch status {
	case model.PathObservationStatusObserved:
		return "Observed"
	case model.PathObservationStatusUnsupported:
		return "Unsupported"
	case model.PathObservationStatusError:
		return "Error"
	default:
		return "Unknown"
	}
}

func labelForHopState(state model.PathHopState) string {
	switch state {
	case model.PathHopStateObserved:
		return "Observed responder"
	case model.PathHopStateUnobservable:
		return "Unobservable"
	default:
		return "Unknown"
	}
}

func detailForHopState(state model.PathHopState) string {
	switch state {
	case model.PathHopStateObserved:
		return "A responder was observed at this TTL."
	case model.PathHopStateUnobservable:
		return "No responder was observed at this TTL; this is not packet loss."
	default:
		return "The observation state is not known."
	}
}

func labelForSegmentKind(kind model.PathSegmentKind) string {
	switch kind {
	case model.PathSegmentObservedResponder:
		return "Observed responder"
	case model.PathSegmentInferred:
		return "Inferred transit range"
	case model.PathSegmentUnobservable:
		return "Unobservable range"
	default:
		return "Unknown segment"
	}
}

func detailForSegmentKind(kind model.PathSegmentKind) string {
	switch kind {
	case model.PathSegmentObservedResponder:
		return "Direct responder evidence for this TTL."
	case model.PathSegmentInferred:
		return "Bounded inference between observations; not an exact physical link."
	case model.PathSegmentUnobservable:
		return "No responder was observed in this TTL range; this is not packet loss."
	default:
		return "The segment type is not known."
	}
}

func portLabel(port uint16) string {
	if port == 0 {
		return "destination port unspecified"
	}
	return fmt.Sprintf("destination port %d", port)
}

func pluralSuffix(count int) string {
	if count == 1 {
		return ""
	}
	return "s"
}

func uniqueStrings(values []string) []string {
	if len(values) < 2 {
		return values
	}
	seen := make(map[string]struct{}, len(values))
	result := make([]string, 0, len(values))
	for _, value := range values {
		if _, ok := seen[value]; ok {
			continue
		}
		seen[value] = struct{}{}
		result = append(result, value)
	}
	return result
}
